import QueryProvider from "@/providers/QueryProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<QueryProvider>
					<section className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-b from-purple-50 to-blue-100 p-4">
						<div className="w-full max-w-md mx-auto flex flex-col items-center justify-center space-y-8 relative">
							{children}
						</div>
					</section>
					<Toaster richColors />
				</QueryProvider>
			</body>
			<Script
				src="https://developers.kakao.com/sdk/js/kakao.js"
				strategy="afterInteractive"
			/>
		</html>
	);
}
